### ISSUE TITLE
Not Null constraint tries to get applied to a computed column

### ISSUE THREAD

**Issue by dustin-H** [fullstack-build/fullstack-one#18]
When I create a computed column like this

```
finishedProduction: Boolean! @computed(expression: "FinishedProduction", params: {})
```

the migration will try to add a NOT NULL Constraint to a not existing column:

```
one:3407d7:DbSchemaBuilder:trace 2018-11-22T00:31:37+0100 <trace> index.js:235 (DbSchemaBuilder.<anonymous>) migration.sql.statement ALTER TABLE "public"."Order" ALTER COLUMN "finishedProduction" SET NOT NULL; +1ms
  one:3407d7:DbSchemaBuilder:warn  2018-11-22T00:31:37+0100 <warn> index.js:256 (DbSchemaBuilder.<anonymous>) migration.rollback +1ms
  one:3407d7:AutoMigrate:warn  2018-11-22T00:31:37+0100 <warn> index.js:73 (AutoMigrate.<anonymous>) runMigration.error { error: column "finishedProduction" of relation "Order" does not exist
  one:3407d7:AutoMigrate:warn     at Connection.parseE (/Users/hex0r/GitLab/doenastie/backend/node_modules/pg/lib/connection.js:554:11)
  one:3407d7:AutoMigrate:warn     at Connection.parseMessage (/Users/hex0r/GitLab/doenastie/backend/node_modules/pg/lib/connection.js:379:19)
  one:3407d7:AutoMigrate:warn     at Socket.<anonymous> (/Users/hex0r/GitLab/doenastie/backend/node_modules/pg/lib/connection.js:119:22)
  one:3407d7:AutoMigrate:warn     at Socket.emit (events.js:182:13)
  one:3407d7:AutoMigrate:warn     at Socket.EventEmitter.emit (domain.js:442:20)
  one:3407d7:AutoMigrate:warn     at addChunk (_stream_readable.js:283:12)
  one:3407d7:AutoMigrate:warn     at readableAddChunk (_stream_readable.js:264:11)
  one:3407d7:AutoMigrate:warn     at Socket.Readable.push (_stream_readable.js:219:10)
  one:3407d7:AutoMigrate:warn     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  one:3407d7:AutoMigrate:warn   name: 'error',
  one:3407d7:AutoMigrate:warn   length: 127,
  one:3407d7:AutoMigrate:warn   severity: 'ERROR',
  one:3407d7:AutoMigrate:warn   code: '42703',
  one:3407d7:AutoMigrate:warn   detail: undefined,
  one:3407d7:AutoMigrate:warn   hint: undefined,
  one:3407d7:AutoMigrate:warn   position: undefined,
  one:3407d7:AutoMigrate:warn   internalPosition: undefined,
  one:3407d7:AutoMigrate:warn   internalQuery: undefined,
  one:3407d7:AutoMigrate:warn   where: undefined,
  one:3407d7:AutoMigrate:warn   schema: undefined,
  one:3407d7:AutoMigrate:warn   table: undefined,
  one:3407d7:AutoMigrate:warn   column: undefined,
  one:3407d7:AutoMigrate:warn   dataType: undefined,
  one:3407d7:AutoMigrate:warn   constraint: undefined,
  one:3407d7:AutoMigrate:warn   file: 'tablecmds.c',
  one:3407d7:AutoMigrate:warn   line: '5796',
  one:3407d7:AutoMigrate:warn   routine: 'ATExecSetNotNull' } +3ms
```

However, without `!` everything works fine:

```
finishedProduction: Boolean @computed(expression: "FinishedProduction", params: {})
```

**Comment by terehov** [comment]
solved by replacing own migrations with TypeORM synchronization.
