### ISSUE TITLE
Default uuid tries to get applied to a computed column

### ISSUE THREAD

**Issue by dustin-H** [fullstack-build/fullstack-one#19]
This is very similar to #18.

When trying to add a computed column of Gql-Type `ID`, the migration will try to set the default of the computed column to the uuid-function:

```
storeId: ID @computed(expression: "StoreIdFromOrder")
```

Error: 
```
 one:d490c7:DbSchemaBuilder:trace 2018-11-22T16:21:27+0100 <trace> index.js:235 (DbSchemaBuilder.<anonymous>) migration.sql.statement ALTER TABLE "public"."Order" ALTER COLUMN "storeId" SET DEFAULT _meta.uuid_generate_v4(); +1ms
  one:d490c7:DbSchemaBuilder:warn  2018-11-22T16:21:27+0100 <warn> index.js:256 (DbSchemaBuilder.<anonymous>) migration.rollback +2ms
  one:d490c7:AutoMigrate:warn  2018-11-22T16:21:27+0100 <warn> index.js:73 (AutoMigrate.<anonymous>) runMigration.error { error: column "storeId" of relation "Order" does not exist
  one:d490c7:AutoMigrate:warn     at Connection.parseE (/Users/hex0r/GitLab/doenastie/backend/node_modules/pg/lib/connection.js:554:11)
  one:d490c7:AutoMigrate:warn     at Connection.parseMessage (/Users/hex0r/GitLab/doenastie/backend/node_modules/pg/lib/connection.js:379:19)
  one:d490c7:AutoMigrate:warn     at Socket.<anonymous> (/Users/hex0r/GitLab/doenastie/backend/node_modules/pg/lib/connection.js:119:22)
  one:d490c7:AutoMigrate:warn     at Socket.emit (events.js:182:13)
  one:d490c7:AutoMigrate:warn     at Socket.EventEmitter.emit (domain.js:442:20)
  one:d490c7:AutoMigrate:warn     at addChunk (_stream_readable.js:283:12)
  one:d490c7:AutoMigrate:warn     at readableAddChunk (_stream_readable.js:264:11)
  one:d490c7:AutoMigrate:warn     at Socket.Readable.push (_stream_readable.js:219:10)
  one:d490c7:AutoMigrate:warn     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  one:d490c7:AutoMigrate:warn   name: 'error',
  one:d490c7:AutoMigrate:warn   length: 119,
  one:d490c7:AutoMigrate:warn   severity: 'ERROR',
  one:d490c7:AutoMigrate:warn   code: '42703',
  one:d490c7:AutoMigrate:warn   detail: undefined,
  one:d490c7:AutoMigrate:warn   hint: undefined,
  one:d490c7:AutoMigrate:warn   position: undefined,
  one:d490c7:AutoMigrate:warn   internalPosition: undefined,
  one:d490c7:AutoMigrate:warn   internalQuery: undefined,
  one:d490c7:AutoMigrate:warn   where: undefined,
  one:d490c7:AutoMigrate:warn   schema: undefined,
  one:d490c7:AutoMigrate:warn   table: undefined,
  one:d490c7:AutoMigrate:warn   column: undefined,
  one:d490c7:AutoMigrate:warn   dataType: undefined,
  one:d490c7:AutoMigrate:warn   constraint: undefined,
  one:d490c7:AutoMigrate:warn   file: 'tablecmds.c',
  one:d490c7:AutoMigrate:warn   line: '5853',
  one:d490c7:AutoMigrate:warn   routine: 'ATExecColumnDefault' } +3ms
```

In general db-migrations should just ignore columns with the `@computed` directive completely.

**Comment by terehov** [comment]
solved by replacing own migrations with TypeORM synchronization.
